### ISSUE TITLE
How to use in markdown table?

### ISSUE THREAD

**Issue by pfuhlert** [htmlwidgets/sparkline#11]
Hi,

thanks again for a great package! But I cannot get it to work for my data.table in rmarkdown. Is there a documentation somewhere?

**Comment by ramnathv** [comment]
Provide some reproducible code so I know what you are trying to achieve.

**Comment by timelyportfolio** [comment]
possibly related to https://github.com/renkun-ken/formattable/issues/10

**Comment by pfuhlert** [comment]
Yes it is. a reproducible code can be found in the other issue.

**Comment by timelyportfolio** [comment]
Since over 1 1/2 years old going to close.  There are lots of examples now with `sparkline` in `rmarkdown`.
