### ISSUE TITLE
How to use composite bar in markdown?

### ISSUE THREAD

**Issue by Tazik** [htmlwidgets/sparkline#13]
How can I use composite bar?
When I run this in Rstudio:
`sparkline(as.vector(unlist(table_to_chart$procent_to_call[1] )), type="bar")`

`sparkline(as.vector(unlist(table_to_chart$procent_to_call[1] )), type="line", composite = T)`

I get error:
`Attempted to attach a composite sparkline to an element with no existing sparkline`

**Comment by ramnathv** [comment]
Can you point me to the equivalent javascript code?

**Comment by Tazik** [comment]
I do not now Java. Is there possibility to create composite bar in R ?

**Comment by Tazik** [comment]
@ramnathv 
I'd like to do to something like this:
`$('#sparkline').sparkline([5, 4, 5, -2, 0, 3], { type: 'bar', barColor: '#aaf' });
$('#sparkline').sparkline([4,1,5,7,9,9,8,7,6,6,4,7,8,4,3,2,2,5,6,7], { composite: true, fillColor: false, lineColor: 'red' });`

with that kind of code:
`{"x":{"values":[0,12,22,38,20,32,32,21],"options":{"type":"bar", "height":20,"width":60},"width":60,"height":20},"evals":[]}
{"x":{"values":[0,12,22,38,20,32,32,21],"options":{"composite":true, "type":"line", "height":20,"width":60},"width":60,"height":20},"evals":[]}`

but I do not understand syntax.

**Comment by ramnathv** [comment]
I get it now. This package does not  support composite plots currently, but I have a pending PR that will make that possible. I don't have an ETA on when those changes would get merged in, but when I do merge them in, I will leave a note for you here.

**Comment by Tazik** [comment]
Thanks for response. I can't wait you drop this feature. It'll be very useful for me!

**Comment by jaredlander** [comment]
Did this get merged?

**Comment by danklotz** [comment]
Hm... isn't there any possibility to do in the meantime?

**Comment by timelyportfolio** [comment]
@ramnathv, I would love to see this.  Will push forward with this unless you tell me no :)

**Comment by timelyportfolio** [comment]
@tazik, I'll make this much better, but with the newest Github version of `htmlwidgets`

```
devtools::install_github("ramnathv/htmlwidgets")
```
we get `onRender`, so we could do something like this.

```
# hack to provide composite charts
# https://github.com/htmlwidgets/sparkline/issues/13

library(htmlwidgets)
library(sparkline)

onRender(
  sparkline(
    c(5,4,5,-2,0,3),
    type='bar',
    barColor="#aaf",
    chartRangeMin=-5,
    chartRangeMax=10
  ),
"
function(el,x){
$(el).sparkline(
  [4,1,5,7,9,9,8,7,6,6,4,7,8,4,3,2,2,5,6,7],
  {
    composite: true,
    fillColor: false,
    lineColor: 'red',
    chartRangeMin: -5,
    chartRangeMax: 10
  }
)
}
"
)
```

**Comment by timelyportfolio** [comment]
cc @diegocgaona, if interested in potential new sparkline functionality.

**Comment by timelyportfolio** [comment]
As I work through this, I think a composite function `addComposite` like this would be more flexible.

```
# first install from Github
#devtools::install_github("timelyportfolio/sparkline@update/sparkline")
sl1 <- sparkline(
  c(5,4,5,-2,0,3),
  type='bar',
  barColor="#aaf",
  chartRangeMin=-5,
  chartRangeMax=10,
  # set an id that will make it easier to refer
  #  in the next sparkline
  elementId="sparkline-for-composite"
)
sl2 <- sparkline(
  c(4,1,5,7,9,9,8,7,6,6,4,7,8,4,3,2,2,5,6,7),
  type="line",
  fillColor = FALSE,
  lineColor ='red',
  chartRangeMin = -5,
  chartRangeMax = 10,
  # will need to set composite = TRUE
  composite = TRUE,
  # and set renderSelector to the id we set in the previous sparkline
  renderSelector = "#sparkline-for-composite"
)

# try to make a function to add a composite to an existing sparkline
addComposite <- function(sparkline=NULL, sparklineToAdd=NULL, ...){
  stopifnot(
    !is.null(sparkline),
    inherits(sparkline,"sparkline")
  )
  
  sparkline_options <- list()
  
  # if a sparkline is provided to add
  #   then get its values and options
  if(!is.null(sparklineToAdd)) {
    sparkline_options <- list(
      values = sparklineToAdd$x$values,
      options = sparklineToAdd$x$options
    )
  }
  
  # if ... are provided
  #   then use these for values and options
  if(length(list(...)) > 0) {
    sparkline_options <- modifyList(sparkline_options,list(...))
  }
  
  sparkline_options$options$composite <- TRUE
  sparkline$x$composites[[length(sparkline$x$composites)+1]] <- sparkline_options
  return(sparkline)
}

# add sparkline as a composite
addComposite(sl1, sl2)

# add values and options as a composite
addComposite(
  sl1,
  values=c(4,1,5,7,9,9,8,7,6,6,4,7,8,4,3,2,2,5,6,7),
  options = list(
    type="line",
    fillColor = FALSE,
    lineColor ='red',
    chartRangeMin = -5,
    chartRangeMax = 10
  )
)

# add combination of sparkline and options as a composite
addComposite(
  sl1,
  sl2,
  options = list(
    type="box"
  )
)
```

**Comment by diegocgaona** [comment]
Hi @timelyportfolio , sorry for this dumb question, but how can I install your dev version to test?
thanks!

**Comment by timelyportfolio** [comment]
I will close this for now.  Please reopen if not addressed.  I will open a separate issue for composites of different types no longer lining up.
