### ISSUE TITLE
Use option colorMap with sparkline

### ISSUE THREAD

**Issue by Dzsombre** [htmlwidgets/sparkline#24]
When I am drawing a sparkline I cannot seem to use the colorMap option of sparkline. This option is somehow passed to jQuery, I am probably trying with a wrong syntax, but I cannot figure out, how to do it properly!
Other options listen on the [website](https://omnipotent.net/jquery.sparkline/#bar) of jQuery Sparklines work:

```
library(sparkline)
sparkline::sparkline(round(runif(10,1,10)), type = "bar", spotRadius = 5)
```

But I cannot do the same with colorMap, this is one example how I have tried:
```
sparkline::sparkline(round(runif(10,1,10)), type = "bar", colorMap = {':5': '#ff0' })
```
I have also posted this question on [stackoverflow](https://stackoverflow.com/questions/52167681/how-can-i-add-options-like-colormap-to-sparkline-in-rl).

My goal is to highlight a bar with a certain value.

What am I missing?
Thanks for your help!

**Comment by ramnathv** [comment]
Does this give you what you want?

```r
sparkline::sparkline(
  round(runif(10,1,10)), 
  type = "bar", 
  colorMap = list(`:5` = '#ff0')
)
```

**Comment by Dzsombre** [comment]
It does, thank you very much!
