### ISSUE TITLE
Creating Stacked Bar Charts 

### ISSUE THREAD

**Issue by jackwilliambiggs** [htmlwidgets/sparkline#30]
Is it possible to create stacked bar charts  in R with the sparkline package? 

I have seen that you can indicate a series with jQuery by delimiting by colons. I.e a single stacked bar chart split in half could be "5:5" whereas two bar charts with the values of five would be written "5,5".

I am uncertain of how you would write this in R. Any help would be great thanks

**Comment by timelyportfolio** [comment]
@jackwilliambiggs sorry I missed this.  Did you find an answer?

**Comment by millerjef** [comment]
I, too, would like to do this. @jackwilliambiggs did you find a solution?

**Comment by jackwilliambiggs** [comment]
@timelyportfolio @millerjef  Sorry I seemed to have closed this by mistake. I haven't found a solution and I think moved past it. I still think it would be useful if the author did include the ability to do this or clarify if it can be done with R code
