### ISSUE TITLE
unable to deploy to shinyapps

### ISSUE THREAD

**Issue by pssguy** [htmlwidgets/sparkline#6]
When I try and deploy I get to

    building: Building package: sparkline

    Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
      there is no package called ‘htmltools’
    ERROR: lazy loading failed for package ‘sparkline’
    * removing ‘/usr/local/lib/R/site-library/sparkline’

Not sure if this is a related issue
https://github.com/rstudio/shinyapps/issues/114

**Comment by ramnathv** [comment]
Thanks @pssguy . I got an email highlighting the same issue. I think I goofed up with importing `htmltools` which is what is causing this error. I will push a fix by end of this week to fix this.

**Comment by pssguy** [comment]
Thanks Ramnath  I don't suppose you have come up with a solution tohttps://github.com/htmlwidgets/sparkline/issues/3
  There's an app using WorldBank data which has sparklines in a table in a shiny/rmarkdown format but I cannot deploywith its current behavious
andrew 

     On Tuesday, February 3, 2015 8:00 PM, Ramnath Vaidyanathan <notifications@github.com> wrote:
   
 

 Thanks @pssguy . I got an email highlighting the same issue. I think I goofed up with importing htmltools which is what is causing this error. I will push a fix by end of this week to fix this.—
