### ISSUE TITLE
allow use of the composite option

### ISSUE THREAD

**Issue by timelyportfolio** [htmlwidgets/sparkline#9]
As discussed in this StackOverflow [post](http://stackoverflow.com/questions/29906806/sparklines-in-r-using-html-widgets), the [`composite` parameter](http://omnipotent.net/jquery.sparkline/#common) might be a useful feature.  Looking at the code, it could be hacked, but I thought a pull for proper implementation might prove to be a better route.  I'm happy to tackle, but wanted to make sure @ramnathv is ok with it before plunging in.

**Comment by ramnathv** [comment]
This is already done. I just have to push the branch to github.

**Comment by diegocgaona** [comment]
Hi, the update have been pushed to the branch?
Thanks!!
